### ISSUE TITLE
Posts order

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#1]
The portal order of the posts has to be reversed. Most recent first.

**Comment by russog** [comment]
amended the store proc to order by Created desc

**Comment by corebean** [comment]
This has again been reversed

**Comment by corebean** [comment]
This has again been reversed

**Comment by corebean** [comment]
Okay - so the order of the old posts has been set correctly, but now when I upload a new image it again appears as the last post. Is the display not set in order of upload date/time?????

**Comment by russog** [comment]
No by created time. Do you want me to update the logic?

**Comment by corebean** [comment]
Are you sure this is the "Date Created" order (starting from the latest to
the oldest)? Because I posted the Jockey ones the 1st of November and about
10 minutes later I posted the Hanro one. The order seems to be all over
the  place now...

**Comment by russog** [comment]
To check: http://api.ladenfreude.zeroesapps.com/posts
If this always gives the same result set ask @andor

**Comment by bereczandor** [comment]
Something is wrong in backend. The created date always has the call time.
The snippet is from the posts api call, it is the same date/second for ever post.

"id": 101113,
      "created": 1478197584,
"id": 101114,
      "created": 1478197584,
 "id": 101115,
      "created": 1478197584,

Same happens with the company created date.

If you make a call and look in the response, you will see a new date, but the same date everywhere.

**Comment by russog** [comment]
@corebean could you please check this is now fixed? is so please close it

**Comment by corebean** [comment]
Yes. It appears to have been resolved. For now.

**Comment by corebean** [comment]
Reopening because this is NOT fixed. I just created a new post today and it is again appearing right toward the bottom - but oddly enough it is not the LAST item being displayed. Please fix the post order so the newest posts are ALWAYS showing at the top of the page.
